fx_version 'bodacious'
game 'gta5'

ui_page 'nui/index.html'

client_scripts {
	'@vrp/lib/utils.lua',
	'client.lua'
}

server_scripts {
	'@vrp/lib/utils.lua',
	'server.lua'
}

files {
	'nui/index.html',
	'nui/ui.js',
	'nui/style.css',
	
	'nui/imagens/mochila.png',
	'nui/imagens/celular.png',
	'nui/imagens/radio.png',
	'nui/imagens/mascara.png',
	'nui/imagens/oculos.png',
	'nui/imagens/indentidade.png',
	'nui/imagens/colete.png',
	'nui/imagens/militec.png',
	'nui/imagens/repairkit.png',

	'nui/imagens/dinheiro-sujo.png',
	'nui/imagens/algema.png',
	'nui/imagens/lockpick.png',
	'nui/imagens/capuz.png',
	'nui/imagens/placa.png',
	'nui/imagens/c4.png',
	'nui/imagens/placa.png',
	'nui/imagens/serra.png',
	'nui/imagens/furadeira.png',

	'nui/imagens/agua.png',
	'nui/imagens/leite.png',
	'nui/imagens/cafe.png',
	'nui/imagens/cafecleite.png',
	'nui/imagens/cafeexpresso.png',
	'nui/imagens/capuccino.png',
	'nui/imagens/frappuccino.png',
	'nui/imagens/cha.png',
	'nui/imagens/icecha.png',
	'nui/imagens/sprunk.png',
	'nui/imagens/cola.png',
	'nui/imagens/energetico.png',

	'nui/imagens/pibwassen.png',
	'nui/imagens/tequilya.png',
	'nui/imagens/patriot.png',
	'nui/imagens/blarneys.png',
	'nui/imagens/jakeys.png',
	'nui/imagens/barracho.png',
	'nui/imagens/ragga.png',
	'nui/imagens/nogo.png',
	'nui/imagens/mount.png',
	'nui/imagens/cherenkov.png',
	'nui/imagens/bourgeoix.png',
	'nui/imagens/bleuterd.png',

	'nui/imagens/sanduiche.png',
	'nui/imagens/rosquinha.png',
	'nui/imagens/hotdog.png',
	'nui/imagens/xburguer.png',
	'nui/imagens/chips.png',
	'nui/imagens/batataf.png',
	'nui/imagens/pizza.png',
	'nui/imagens/frango.png',
	'nui/imagens/bcereal.png',
	'nui/imagens/bchocolate.png',
	'nui/imagens/taco.png',
	'nui/imagens/yakisoba.png',

	'nui/imagens/paracetamil.png',
	'nui/imagens/voltarom.png',
	'nui/imagens/trandrylux.png',
	'nui/imagens/dorfrex.png',
	'nui/imagens/buscopom.png',

	'nui/imagens/r-paracetamil.png',
	'nui/imagens/r-voltarom.png',
	'nui/imagens/r-trandrylux.png',
	'nui/imagens/r-dorfrex.png',
	'nui/imagens/r-buscopom.png',

	'nui/imagens/meta-alta.png',
	'nui/imagens/meta-media.png',
	'nui/imagens/meta-baixa.png',

	'nui/imagens/composito-alta.png',
	'nui/imagens/composito-media.png',
	'nui/imagens/composito-baixa.png',

	'nui/imagens/nitrato-amonia.png',
	'nui/imagens/hidroxido-sodio.png',
	'nui/imagens/pseudoefedrina.png',
	'nui/imagens/eter.png',

	'nui/imagens/coca-alta.png',
	'nui/imagens/coca-media.png',
	'nui/imagens/coca-baixa.png',

	'nui/imagens/pasta-alta.png',
	'nui/imagens/pasta-media.png',
	'nui/imagens/pasta-baixa.png',

	'nui/imagens/acido-sulfurico.png',
	'nui/imagens/folhas-coca.png',
	'nui/imagens/calcio-po.png',
	'nui/imagens/querosene.png',

	'nui/imagens/corpo-glock.png',
	'nui/imagens/corpo-magnum44.png',
	'nui/imagens/corpo-ak47.png',
	'nui/imagens/corpo-aks.png',
	'nui/imagens/corpo-uzi.png',

	'nui/imagens/molas.png',
	'nui/imagens/placa-metal.png',
	'nui/imagens/gatilho.png',
	'nui/imagens/capsulas.png',
	'nui/imagens/polvora.png',

	'nui/imagens/diamante.png',
	'nui/imagens/ouro.png',
	'nui/imagens/bronze.png',
	'nui/imagens/ferro.png',
	'nui/imagens/rubi.png',
	'nui/imagens/esmeralda.png',
	'nui/imagens/safira.png',
	'nui/imagens/topazio.png',
	'nui/imagens/ametista.png',
	
	'nui/imagens/diamante2.png',
	'nui/imagens/ouro2.png',
	'nui/imagens/bronze2.png',
	'nui/imagens/ferro2.png',
	'nui/imagens/rubi2.png',
	'nui/imagens/esmeralda2.png',
	'nui/imagens/safira2.png',
	'nui/imagens/topazio2.png',
	'nui/imagens/ametista2.png',

	'nui/imagens/sacodelixo.png',
	'nui/imagens/garrafadeleite.png',
	'nui/imagens/garrafavazia.png',
	'nui/imagens/encomenda.png',
	'nui/imagens/tora.png',
	'nui/imagens/nf.png',

	'nui/imagens/paraquedas.png',
	'nui/imagens/gasolina.png',
	'nui/imagens/sinalizador.png',
	'nui/imagens/extintor.png',
	'nui/imagens/faca.png',
	'nui/imagens/adaga.png',
	'nui/imagens/ingles.png',
	'nui/imagens/machete.png',
	'nui/imagens/canivete.png',
	'nui/imagens/grifo.png',
	'nui/imagens/golf.png',
	'nui/imagens/cabra.png',
	'nui/imagens/machado.png',
	'nui/imagens/lanterna.png',
	'nui/imagens/beisebol.png',
	'nui/imagens/garrafa.png',
	'nui/imagens/batalha.png',
	'nui/imagens/sinuca.png',
	'nui/imagens/pedra.png',
	'nui/imagens/cassetete.png',
	'nui/imagens/glock.png',
	'nui/imagens/magnum44.png',
	'nui/imagens/fiveseven.png',
	'nui/imagens/deserteagle.png',
	'nui/imagens/taser.png',
	'nui/imagens/m4a1.png',
	'nui/imagens/ak47.png',
	'nui/imagens/aks.png',
	'nui/imagens/mp5.png',
	'nui/imagens/uzi.png',
	'nui/imagens/remington.png',
	'nui/imagens/winchester22.png',

	'nui/imagens/m-paraquedas.png',
	'nui/imagens/combustivel.png',
	'nui/imagens/m-sinalizador.png',
	'nui/imagens/m-extintor.png',
	'nui/imagens/m-glock.png',
	'nui/imagens/m-magnum44.png',
	'nui/imagens/m-fiveseven.png',
	'nui/imagens/m-deserteagle.png',
	'nui/imagens/m-taser.png',
	'nui/imagens/m-m4a1.png',
	'nui/imagens/m-ak47.png',
	'nui/imagens/m-aks.png',
	'nui/imagens/m-mp5.png',
	'nui/imagens/m-uzi.png',
	'nui/imagens/m-remington.png',
	'nui/imagens/m-winchester22.png'
}